name: build-sqlite

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      AWS_S3_WRITE_ACCESS_KEY: ${{ secrets.AWS_S3_WRITE_ACCESS_KEY }}
      AWS_S3_WRITE_SECRET_KEY: ${{ secrets.AWS_S3_WRITE_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Build sqlite DB
      run: |
        RUBYOPT="-W0" rake all
